import sys
import os

def create_skill(name, description, instructions):
    path = f".agent/skills/{name}.skill"
    content = f"""---
name: {name}
description: "{description}"
---

# {name.replace('-', ' ').title()}

## Core Instructions
{instructions}

## Generated by The Side Hustle JIT Orchestrator
"""
    os.makedirs(".agent/skills", exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"Forged new skill: {path}")

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: python skill_forge.py [name] [desc] [instructions]")
    else:
        create_skill(sys.argv[1], sys.argv[2], sys.argv[3])
